name: test

on:
  - push
  - workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '>=1.19.4'
        cache: true
    - name: Tests
      run: go test -coverprofile cover.out -v ./...
    - name: Coverage
      run: go tool cover -func=cover.out
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '>=1.19.4'
        cache: true
    - name: Style
      run: |
        echo "::group::Ensuring everything is tidy"
        go mod tidy
        go fmt ./...
        echo "::endgroup::"

        if [[ ! -z "$(git status --porcelain)" ]]
        then
          echo '⚠️ Need to rerun `go mod tidy` and/or `go fmt`' >> $GITHUB_STEP_SUMMARY
          exit 1
        fi

        echo '✅ All good!' >> $GITHUB_STEP_SUMMARY

